### ISSUE TITLE
Psite function error message

### ISSUE THREAD

**Issue by mandiedriskill** [LabTranslationalArchitectomics/riboWaltz#15] opened 2018-12-28 20:01 UTC
Hello,

I was wondering if you had any suggestion with an error message I get when I try to run the psite function. This is the error I recieved:
processing nuc_genome_102617_RF-15Dark_Rep1_merged.fastqAligned.toTranscriptome.out
no non-missing arguments to min; returning Infno non-missing arguments to max; returning -InfError in if (extremity == "auto" & ((best_from3_tab[, perc] > best_from5_tab[,  : 
  argument is of length zero

The create_annotation function seemed work:
Nuc_only_GTF<-"/Users/mandiedriskill/Desktop/Barkan_Project/Ribowaltz/nuc_only.gtf"
Nuc_only_annotation<-create_annotation(gtfpath=Nuc_only_GTF)

In addition, the bamtolist function seemed work:
bamfolder<-"/Users/mandiedriskill/Desktop/Barkan_Project/Ribowaltz/trans_bam_folder"
Nuc_only_bam_list<-bamtolist(bamfolder, Nuc_only_annotation, transcript_align = TRUE, name_samples = NULL, rm_version = FALSE, granges = FALSE)

This is what I did for the psite function:
p<-psite(Nuc_only_bam_list, flanking = 6, start = TRUE, extremity = "auto", plot = TRUE, plot_dir = NULL, plot_format = "png", cl = 95)

Any help would be much appreciated.

**Comment by mandiedriskill** [comment] 2019-01-02 19:22
Hello,
Thank you very much for getting back to me so fast. 
I tried data( Nuc_only_annotation) and data(Nuc_only_bam_list)
This gives me the following error:
data set ‘Nuc_only_annotation’ not found
data set ‘Nuc_only_bam_list’ not found

In addition,  rlength_distr and rends_heat do not work.

You are correct there does seem to be a problem with generating correct data.tables. The weird thing is when I print(Nuc_only_annotation) and print(Nuc_only_bam_list), I get out data with values. 
> print(Nuc_only_annotation)
                transcript l_tr l_utr5 l_cds l_utr3
     1: ENSRNA049453565-T1  145      0     0      0
     2: ENSRNA049453582-T1   75      0     0      0
     3: ENSRNA049453693-T1   74      0     0      0
     4: ENSRNA049453717-T1   90      0     0      0
     5: ENSRNA049453784-T1  185      0     0      0
    ---                                            
133907:         zma-mir482   32      0     0      0
133908:        zma-mir528a  123      0     0      0
133909:        zma-mir528b   78      0     0      0
133910:         zma-mir529  126      0     0      0
133911:         zma-mir827  122      0     0      0

> print(Nuc_only_bam_list)
$`nuc_genome_102617_RF-15Dark_Rep1_merged.fastqAligned.toTranscriptome.out`
             transcript end5 end3 length cds_start cds_stop
 1: Zm00001d003457_T001  281  331     51        70      684
 2: Zm00001d043543_T006  268  318     51        66     2597
 3: Zm00001d043543_T001  364  414     51       162     2795
 4: Zm00001d043543_T003  364  414     51       162     1565
 5: Zm00001d043543_T002  364  414     51       162     2993
 6: Zm00001d043543_T004  364  414     51      1880     3394
 7: Zm00001d028117_T004 1045 1095     51       933     1409
 8: Zm00001d028117_T003  514  564     51        96      878
 9: Zm00001d028117_T002  514  564     51        96      878
10: Zm00001d028117_T001  514  564     51        96      878
---

I aligned with STAR with the same GTF file and all reference genome files came from the same site Gramene.org.  I also used the flag --quantMode TranscriptomeSAM. In addition, I loaded the libraries devtools and riboWaltz before running any lines. Any suggestions would be greatly appreciated.
Thank you,
Mandie

**Comment by fabiolauria** [comment] 2019-01-07 15:06
Hi Mandie,
I checked the code of riboWaltz out for any bugs or wrong lines explaining your issues. I didn't find anything.
Looking at the first lines of your data everything seems ok, too. However, I have a couple of questions for you:
1) are there genes with annotated UTRs and CDS? The output of print(Nuc_only_annotation) suggests the last three columns are filled with 0s and only the length of the whole transcript (l_tr) is known. If this is the case many functions included in riboWaltz are not going to work, especially those providing graphical outputs.
2) could you please send me a chunk of the data.table reported above (i.e. the first data.table of you input list, I guess)? The first 500 rows as a zipped RData should be enough for me to try and find out why rlength_distr doesn't work. Starting from there, I can figure out if the problem is the data structure or riboWaltz and tell you something more.

A last general comment: all reads listed by print(Nuc_only_bam_list) are quite long for a common ribosome profiling assay. Ribosomes should cover around 28-30 nt while in your case the fragments are 51 nts long. Did you apply some sort of filter?

Bests,
Fabio

**Comment by fabiolauria** [comment] 2019-01-10 08:40
Hi Mendie,
the annotation file seems ok, so could you please send me a chunk of the other data.table showed above (the one with mapped reads, from print(Nuc_only_bam_list))?
To perform multiple test on your data, it would be better if the sub-data.table contained data associated to the very same transcripts included in the annotation file you already sent me.

Regarding point 3 of your answer, which kind of original files did you use for assessing the read lengths? Did you look at BED files directly generated from BAMs? If so, and original reads are between 20-35 nts long, the whole problem would be reduced to a wrong translation of data from BAM to data.tables. It may be worth verifying this hypothesis. 

Bests,
Fabio

**Comment by fabiolauria** [comment] 2019-05-17 07:41
Hi Mendie,
I guess you have cleared your doubts or chosen another tool, so I'm closing this issue for now.
If you need some more help please don't hesitate to contact me again.

Bests
Fabio

**Closed by fabiolauria** 2019-05-17 07:41 UTC
