### ISSUE TITLE
psite_info & codon_usage_psite error in evaluating the argument 'x' in selecting a method for function 'subseq'

### ISSUE THREAD

**Issue by ChristianRohde** [LabTranslationalArchitectomics/riboWaltz#66] opened 2023-03-14 12:41 UTC
Hi,

I used riboWaltz successfully 3 years ago. Now with new data as well as the old data & the old script some functions of your software fail. I tried with 2 different R installations both from command line as well as from RStudio server Script and RMD. Please find more information below.

My issue sounds very similar as https://github.com/LabTranslationalArchitectomics/riboWaltz/issues/39 but I think it might have a different source. When I run the function **psite_info** and **codon_usage_psite** I get the following error: _Error in h(simpleError(msg, call)) : error in evaluating the argument 'x' in selecting a method for function 'subseq': subscript contains invalid names_. As you suggested in the issue mentioned above I did the check of my transcript names and it all fits to my understanding very well, see below.  

However, when I go into the function and try to understand the problem I find that I can build the **exon** data.table based on **temp_sequences** from the fasta which I provide but that the script fails with subsequent steps such that in the end the **sequences** object is empty. At this step I am not sure what exactly is the source of the problem. For example I can populate the sub_exon_plus table if I omit the 'as.character(names) %in% names(temp_sequences)' part. Does this hint for a problem in data.table filtering or could it be that somehow the GenomicFeatures::exonsBy generated exon data.table has different colnames than expected: I do not find the column **names** in there. 

Best,
Christian

#################################### ####################################
R version 4.2.2 Patched (2022-11-10 r83330)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS

riboWaltz_1.2.0  
devtools_2.4.5
Biostrings_2.66.0   
GenomeInfoDb_1.34.9 
data.table_1.14.8
dplyr_1.1.0        

#################################### #################################### 
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.2 LTS

riboWaltz_1.2.0       
devtools_2.4.5
Biostrings_2.62.0     
GenomeInfoDb_1.30.1
data.table_1.14.8
dplyr_1.1.0 

########################################################################
1) psite_info
reads_psite_list <- riboWaltz::psite_info(
  reads_list, 
  psite_offset,
  site = c("psite", "asite", "esite"),
  fastapath = "Homo_sapiens.GRCh38.cdna.all.fasta",
  gtfpath = "Homo_sapiens.GRCh38.101.gtf",
  fasta_genome = TRUE,
  refseq_sep = NULL,
  bsgenome = NULL,
  txdb = NULL,
  dataSource = NA,
  organism = NA,
  output_class = "datatable"
)

Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
processing sample1
1. adding p-site position
2. adding transcript region
3. adding nucleotide sequence(s)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'subseq': subscript contains invalid names

########################################################################
2) codon_usage_psite
example_cu_barplot <- riboWaltz::codon_usage_psite(
  reads_psite_list, 
  annotation_dt, 
  sample = samples[i],
  fastapath = "~/SDS@HD/sd17e001/genomes_mapping/human_cDNA_transcriptme_bowtie_RiboFootprinting/Homo_sapiens.GRCh38.cdna.all.fasta",
  fasta_genome = TRUE, 
  gtfpath = "~/SDS@HD/sd17e001/genomes_mapping/GTF_annotation/Homo_sapiens.GRCh38.101.gtf",
  frequency_normalization = FALSE,
  refseq_sep = "."
) 

Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'subseq': subscript contains invalid names

########################################################################
3) test transcript names
fasta_sequences <- Biostrings::readDNAStringSet(
  "~/SDS@HD/sd17e001/genomes_mapping/human_cDNA_transcriptme_bowtie_RiboFootprinting/Homo_sapiens.GRCh38.cdna.all.fasta",
  format = "fasta",
  use.names = TRUE
)
names(fasta_sequences) <- tstrsplit(names(fasta_sequences), ".", fixed = TRUE, keep = 1)[[1]]
transcript_names <- unique(reads_list[[1]]$transcript)

# > head(names(fasta_sequences))
# [1] "ENST00000632684" "ENST00000434970" "ENST00000448914" "ENST00000415118" "ENST00000631435" "ENST00000390583"

# > head(transcript_names)
# [1] "ENST00000390454" "ENST00000390443" "ENST00000571766" "ENST00000390627" "ENST00000390533" "ENST00000390531"

# > length(intersect(transcript_names, names(fasta_sequences)))
# [1] 120048
# > length(setdiff(transcript_names, names(fasta_sequences)))
# [1] 0
# > length(setdiff(names(fasta_sequences), transcript_names))
# [1] 67578

**Comment by fabiolauria** [comment] 2023-03-16 09:27
Hi Christian,
thanks for still using riboWaltz and for your detailed issue. 
As you said, it seems the problem is not related to the transcript names in the FASTA or in the list of reads. But it is also true that the Error you got is likely to be associated to mismatching strings. What is remaining is the annotation object coming from the Txdb/GTF. 
You mentioned:

> I can populate the sub_exon_plus table if I omit the 'as.character(names) %in% names(temp_sequences)' part

The current version of the two functions of riboWaltz includes:

`as.character(seqnames) %in% names(temp_sequences)`

with **seqnames** instead of **names**. Are you sure you have the latest version of riboWaltz?

If so, the only option I can see is for me to try and check what is going on using your FASTA and the Txdb/GTF object. If you think this is a good option, you can send me the two files or the link of the specific version of the two  you used in your code.

It will take a bit of time but without the data is pretty difficult.
Let me know what you think.

Best
Fabio

**Comment by ChristianRohde** [comment] 2023-03-16 10:05
Hi Fabio,

thank you for your help. Indeed I did a wrong quote since seqnames is expected to be matched against names(temp_sequences). Sorry for this, it looks like I modifed it already. I agree names does not make any sense at all if I look at it again. But I am confused now: 

does the script want to match chromosomes or transcript-IDs here? Should I upload the fasta of the genome or the fasta of cDNA from the transcriptome to which I mapped? My old scripts hints towards a cDNA.fasta. But if I upload my fasta of transcripts then names(temp_sequences) are transcripts and not chromosomes. I can upload the genome.fasta to **psite_info** function and it will work since now the match is OK, but I am not sure if this helps here. On the other hand I still get the same error with **codon_usage_psite** when I upload the genome.fasta.

Best,
Christian

**Comment by fabiolauria** [comment] 2023-03-16 10:34
Hi Christian,
sorry for the mess, I'll try to be clearer.

There are two options:
1) you mapped your reads on a FASTA file which includes sequences of chromosomes, using proper options to get BAM files with transcript coordinates. In this case, you must upload the original FASTA (with chromosome sequences). The integration with the GTF/txdb object to retrieve of exons etc. is aimed at getting the sequence of the transcripts. Parameter _fasta_genome_ should be set to TRUE.
2) you mapped your read on a FASTA file which includes sequences of transcripts. If this is the case, you must upload the original FASTA (with transcript sequences) and neither _gtfpath_ nor _txdb_ are required. Parameter _fasta_genome_ should be set to FALSE.

Which path did you follow?

Best
Fabio

**Comment by ChristianRohde** [comment] 2023-03-16 13:12
Hi Fabio,

I followed option 2. You are right: it looks like that I was using the parameters wrong. I am very sorry that I bothered you with this. Thank you for reminding me that fasta_genome = FALSE is crucial when analyzing cDNA mapped data in psite_info and codon_usage_psite functions. Next, for my data I also needed to add the refseq_sep="." to bamtolist, psite_info and codon_usage_psite. Now it perfectly works once I strictly apply both settings.

Best,
Christian

**Comment by fabiolauria** [comment] 2023-03-16 13:23
Hi Christian.
I'm happy to hear everything is fine now.
Don't worry about the issue, it's useful for me to understand if and how I can improve the documentation.

I'm going to close this thread, but feel free to reopen it (or other issues if not related to this topic).

Best
Fabio

**Closed by fabiolauria** 2023-03-16 13:23 UTC
