### ISSUE TITLE
wired metaplot using meta profile_psite

### ISSUE THREAD

**Issue by trista1115** [LabTranslationalArchitectomics/riboWaltz#78] opened 2024-04-11 06:38 UTC
Hi Fabio,

I'm attempting to create a metaplot using the metaprofile_psite function. In the figure below, the last blue sample for the 3nt appears to have shifted to the left. Do you have any insights into this?
<img width="446" alt="image" src="https://github.com/LabTranslationalArchitectomics/riboWaltz/assets/66661917/229a9dff-d195-4f5b-a3a2-f4c6f8052f89">

Any insights or suggestions would be greatly appreciated. 
Thank you in advance for your help!

Trista

**Comment by fabiolauria** [comment] 2024-04-11 10:04
H i Trista,
thank you for using riboWaltz.
I think that shift is likely caused by the "wrong" identification of the P-site. In the past, I observed this trend when, for some read lengths, the signal related to the start codon was lower than the signal on a codon downstream (often the 5th codon). It looks like this also in your profile, where you have higher peaks at the beginning of the coding sequence than on the start codon. Usually, the P-site offset computed for the sample showing the shift was greater (or smaller, depending on the optimal read extremity) than all the others.
This is the reason why I introduced the _flanking_ parameter in function **psite**. According to your metaprofile, I think you can try and increase the flanking region to 10 (default is 6). Might be too much, but the idea is to exclude the possibility that reads which are supposed not to have their P-site on the start codon are incorrectly used are reference.

Let me know if this trick works or not.

Best
Fabio

**Comment by trista1115** [comment] 2024-04-11 10:46
Thank you for your prompt response! It worked perfectly. I appreciate your help!

<img width="704" alt="image" src="https://github.com/LabTranslationalArchitectomics/riboWaltz/assets/66661917/a91d87d4-8707-4908-8101-054427077ba5">

Best
Trista

**Comment by fabiolauria** [comment] 2024-04-11 12:26
Good!
I'll close this issue then. Feel free to open new ones if needed.

Best
Fabio

**Closed by fabiolauria** 2024-04-11 12:26 UTC
