### ISSUE TITLE
create_annotation could not work on gtf file from ncbi

### ISSUE THREAD

**Issue by Xuan0318** [LabTranslationalArchitectomics/riboWaltz#34] opened 2021-02-04 07:18 UTC
Hi,

The create_annotation works well on the gtf file from the ensemble. But it could not be used on the gtf file from ncbi. 
```
 #gtf-version 2.2
#!genome-build GRCh38
#!genome-build-accession NCBI_Assembly:GCA_000001405.15
#!annotation-date 01/25/2019
#!annotation-source NCBI Homo sapiens Updated Annotation Release 109.20190125
chr1    BestRefSeq      gene    11874   14409   .       +       .       gene_id "DDX11L1"; db_xref "GeneID:100287102"; db_xref "HGNC:HGNC:37102"; description "DEAD/H-b
ox helicase 11 like 1"; gbkey "Gene"; gene "DDX11L1"; gene_biotype "transcribed_pseudogene"; pseudo "true"; 
chr1    BestRefSeq      exon    11874   12227   .       +       .       gene_id "DDX11L1"; transcript_id "NR_046018.2"; db_xref "GeneID:100287102"; gbkey "misc_RNA"; g
ene "DDX11L1"; product "DEAD/H-box helicase 11 like 1"; exon_number "1"; 
chr1    BestRefSeq      exon    12613   12721   .       +       .       gene_id "DDX11L1"; transcript_id "NR_046018.2"; db_xref "GeneID:100287102"; gbkey "misc_RNA"; g
ene "DDX11L1"; product "DEAD/H-box helicase 11 like 1"; exon_number "2"; 
chr1    BestRefSeq      exon    13221   14409   .       +       .       gene_id "DDX11L1"; transcript_id "NR_046018.2"; db_xref "GeneID:100287102"; gbkey "misc_RNA"; g
ene "DDX11L1"; product "DEAD/H-box helicase 11 like 1"; exon_number "3"; 
chr1    BestRefSeq      gene    14362   29370   .       -       .       gene_id "WASH7P"; db_xref "GeneID:653635"; db_xref "HGNC:HGNC:38034"; description "WAS protein 
family homolog 7, pseudogene"; gbkey "Gene"; gene "WASH7P"; gene_biotype "transcribed_pseudogene"; gene_synonym "FAM39F"; gene_synonym "WASH5P"; pseudo "true"; 
chr1    BestRefSeq      exon    29321   29370   .       -       .       gene_id "WASH7P"; transcript_id "NR_024540.1"; db_xref "GeneID:653635"; gbkey "misc_RNA"; gene 
"WASH7P"; product "WAS protein family homolog 7, pseudogene"; exon_number "1"; 
chr1    BestRefSeq      exon    24738   24891   .       -       .       gene_id "WASH7P"; transcript_id "NR_024540.1"; db_xref "GeneID:653635"; gbkey "misc_RNA"; gene 
"WASH7P"; product "WAS protein family homolog 7, pseudogene"; exon_number "2"; 
chr1    BestRefSeq      exon    18268   18366   .       -       .       gene_id "WASH7P"; transcript_id "NR_024540.1"; db_xref "GeneID:653635"; gbkey "misc_RNA"; gene 
"WASH7P"; product "WAS protein family homolog 7, pseudogene"; exon_number "3"; 
chr1    BestRefSeq      exon    17915   18061   .       -       .       gene_id "WASH7P"; transcript_id "NR_024540.1"; db_xref "GeneID:653635"; gbkey "misc_RNA"; gene 
"WASH7P"; product "WAS protein family homolog 7, pseudogene"; exon_number "4"; 
chr1    BestRefSeq      exon    17606   17742   .       -       .       gene_id "WASH7P"; transcript_id "NR_024540.1"; db_xref "GeneID:653635"; gbkey "misc_RNA"; gene 
"WASH7P"; product "WAS protein family homolog 7, pseudogene"; exon_number "5"; 
chr1    BestRefSeq      exon    17233   17368   .       -       .       gene_id "WASH7P"; transcript_id "NR_024540.1"; db_xref "GeneID:653635"; gbkey "misc_RNA"; gene 
"WASH7P"; product "WAS protein family homolog 7, pseudogene"; exon_number "6"; 
chr1    BestRefSeq      exon    16858   17055   .       -       .       gene_id "WASH7P"; transcript_id "NR_024540.1"; db_xref "GeneID:653635"; gbkey "misc_RNA"; gene 
"WASH7P"; product "WAS protein family homolog 7, pseudogene"; exon_number "7"; 
chr1    BestRefSeq      exon    16607   16765   .       -       .       gene_id "WASH7P"; transcript_id "NR_024540.1"; db_xref "GeneID:653635"; gbkey "misc_RNA"; gene 
"WASH7P"; product "WAS protein family homolog 7, pseudogene"; exon_number "8"; 
chr1    BestRefSeq      exon    15796   15947   .       -       .       gene_id "WASH7P"; transcript_id "NR_024540.1"; db_xref "GeneID:653635"; gbkey "misc_RNA"; gene 
"WASH7P"; product "WAS protein family homolog 7, pseudogene"; exon_number "9"; 
chr1    BestRefSeq      exon    14970   15038   .       -       .       gene_id "WASH7P"; transcript_id "NR_024540.1"; db_xref "GeneID:653635"; gbkey "misc_RNA"; gene 
"WASH7P"; product "WAS protein family homolog 7, pseudogene"; exon_number "10"; 
chr1    BestRefSeq      exon    14362   14829   .       -       .       gene_id "WASH7P"; transcript_id "NR_024540.1"; db_xref "GeneID:653635"; gbkey "misc_RNA"; gene 
"WASH7P"; product "WAS protein family homolog 7, pseudogene"; exon_number "11"; 
```
Is there any other way to generate the annotation file from the ncbi file? Thank you in advance.

**Comment by fabiolauria** [comment] 2021-02-04 08:21
Hi.
What kind of error do you get running _create_annotation_ on GTFs from NCBI?
I just downloaded the human GTF and try and run _create_annotation_ on it. Problem is, this GTF has internal inconsistencies, meaning that some CDSs are not associated with any exon. This causes errors when the file is acquired by _makeTxDbFromGFF_ (from GenomicFeatures), called by _create_annotation_:

```
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... Error in .make_splicings(exons, cds, stop_codons) : 
  some CDS cannot be mapped to an exon
```

Is this the what you get?

Best
Fabio

**Comment by Xuan0318** [comment] 2021-02-04 09:25
Hi Fabio,

Thank you for your reply. Yes, here is the output
`
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... Error in .make_splicings(exons, cds, stop_codons) : 
  some CDS cannot be mapped to an exon
In addition: Warning message:
In .get_cds_IDX(mcols0$type, mcols0$phase) :
  The "phase" metadata column contains non-NA values
  for features of type stop_codon. This information
  was ignored.`
I find this issue in the GenomicFeatures issue: https://github.com/Bioconductor/GenomicFeatures/issues/26
It means that this annotation version is not a stable collection of sequences. But bowtie use this version to create the index for user download. 
There are a lot of CDS data without exon number:
`grep '"CDS"' GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.gtf | grep -v  exon_number
chr1    Gnomon  CDS     144875032       144875080       .       -       0       gene_id "LOC107985528"; transcript_id "unknown_transcript_1"; db_xref "GeneID:107985528"; exception "rearrangement required for product"; gbkey "CDS"; gene "LOC107985528"; product "immunoglobulin kappa variable 1-39-like"; 
chr1    Gnomon  CDS     144874588       144874907       .       -       2       gene_id "LOC107985528"; transcript_id "unknown_transcript_1"; db_xref "GeneID:107985528"; exception "rearrangement required for product"; gbkey "CDS"; gene "LOC107985528"; product "immunoglobulin kappa variable 1-39-like"; 
chr1    Gnomon  start_codon     144875078       144875080       .       -       0       gene_id "LOC107985528"; transcript_id "unknown_transcript_1"; db_xref "GeneID:107985528"; exception "rearrangement required for product"; gbkey "CDS"; gene "LOC107985528"; product "immunoglobulin kappa variable 1-39-like"; 
chr1    Gnomon  stop_codon      144874585       144874587       .       -       0       gene_id "LOC107985528"; transcript_id "unknown_transcript_1"; db_xref "GeneID:107985528"; exception "rearrangement required for product"; gbkey "CDS"; gene "LOC107985528"; product "immunoglobulin kappa variable 1-39-like"; 
^C`
The easy way is to delete these data. But I do not know it will effect result or not. Or I need to create index and do alignment again, it will waste a lot of time. 

Best,
Yuxuan

**Comment by fabiolauria** [comment] 2021-02-04 10:31
Hi Yuxuan.
Since the issues occurs because of the annotation version and how _makeTxDbFromGFF_ handles it, I see only one option here for not wasting to much time: remove all the transcripts without exons from the GTF and then run _create_annotation_. This procedure will affect the import of BAM files (using _bamtolist_) that are likely to include reads mapping on the discarded transcripts. To have a rough idea on the effect of this approach remember that _bamtolist_ returns he percentage of reads discarded because of mismatching IDs between the annotation data table and the BAM files.
Obviously, if the discarded transcripts don't have any corresponding sequence in the FASTA file (I don't know why exons are missing so there might be no sequence as well) nothing is going to change. 

Let me know how it goes or if you have any other idea or solution.

Best
Fabio

**Comment by Xuan0318** [comment] 2021-02-04 10:33
Hi Fabio,

I found all the ncbi gtf file have the same issue, some CDS could not map to exon because they could not be mapped to the known transcript. You could see the output that these gene's id is "unknown_transcript_1"
```
>grep '"CDS"' GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.gtf | grep -v  exon_number
chr1    Gnomon  CDS     144875032       144875080       .       -       0       gene_id "LOC107985528"; transcript_id "unknown_transcript_1"; db_xref "GeneID:107985528"; exception "rearrangement required for product"; gbkey "CDS"; gene "LOC107985528"; product "immunoglobulin kappa variable 1-39-like"; 
chr1    Gnomon  CDS     144874588       144874907       .       -       2       gene_id "LOC107985528"; transcript_id "unknown_transcript_1"; db_xref "GeneID:107985528"; exception "rearrangement required for product"; gbkey "CDS"; gene "LOC107985528"; product "immunoglobulin kappa variable 1-39-like"; 
chr1    Gnomon  start_codon     144875078       144875080       .       -       0       gene_id "LOC107985528"; transcript_id "unknown_transcript_1"; db_xref "GeneID:107985528"; exception "rearrangement required for product"; gbkey "CDS"; gene "LOC107985528"; product "immunoglobulin kappa variable 1-39-like"; 
chr1    Gnomon  stop_codon      144874585       144874587       .       -       0       gene_id "LOC107985528"; transcript_id "unknown_transcript_1"; db_xref "GeneID:107985528"; exception "rearrangement required for product"; gbkey "CDS"; gene "LOC107985528"; product "immunoglobulin kappa variable 1-39-like"; 
^C
```
Then I tested how many genes are in this condition:
```
>grep '"CDS"' GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.gtf | grep -v  exon_number | wc -l
3213
>grep '"CDS"' GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.gtf | wc -l                       
1700052
>cat GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.gtf | wc -l
3694365
```
It means that only 3213 genes have this issue. So I think it will not effect the result if I remove them.
I will try this way.

Best,
Yuxuan

**Comment by Xuan0318** [comment] 2021-02-09 04:03
Hi Fabio,

Removing these lines do work for create_annotaion.
Then I find the index from bowtie used gi number as the annotation. So, I use the fasta file from genecode to run bowtie. Then the ribo_Waltz works well. 
```
Reading timmed_3_timmed_5_cutadtapterv2_SRR8836121.fastq.genecode.bam
Input reads: 0.929 M
Good! Number of indel below indel_threshold for all reads. No reads removed.
0.044 M  (4.771 %) reads removed: reference transcript IDs not found in annotation table.
0.340 M  (38.376 %) reads removed: mapping on negative strand.
Output reads: 0.545 M
Done! timmed_3_timmed_5_cutadtapterv2_SRR8836121.fastq.genecode.bam has been loaded as timmed_3_timmed_5_cutadtapterv2_SRR8836121.fastq.genecode 
```
But I don't know why there are a lot of reads removed because of mapping on negative strand.
I used Comprehensive gene annotation gtf (All region) as annotation file and transcript sequences (CHR region) as the input. 
Thank you in advance.

Best,
Yuxuan

**Comment by Xuan0318** [comment] 2021-02-09 04:17
By the way, I know you are the expert on the ribo-seq analysis. I just wonder do I need to add "-m" option which lets bowtie forbids the muti-mapping reads export to bam/sam. I think it is confused if ribo-seq small reads map to more than one transcript. But it will cause nearly 40% of reads to remove in the bowtie.

```
bowtie:
-m <int> | Suppress all alignments for a particular read or pair if more than <int> reportable alignments exist for it. Reportable alignments are those that would be reported given the -n, -v, -l, -e, -k, -a, --best, and --strata options. Default: no limit. Bowtie is designed to be very fast for small -m but bowtie can become significantly slower for larger values of -m. If you would like to use Bowtie for larger values of -k, consider building an index with a denser suffix-array sample, i.e. specify a smaller -o/--offrate when invoking bowtie-build for the relevant index (see the Performance tuning section for details).
```
Thank you for your help all the time.

Best,
Yuxuan

**Comment by fabiolauria** [comment] 2021-02-09 08:09
Hi Yuxuan,

I'm happy to see you solved the problem with the annotations.

Regarding your comment

> But I don't know why there are a lot of reads removed because of mapping on negative strand

you are right, it's odd. Since you used Bowtie, I guess you directly mapped on the transcriptome, so the percentage of reads mapping on the negative strand should be very low (< 2%). Different story for alignments on the genome that return bam files based on transcript coordinates. In this case the parameter _transcript_align_ should be set to FALSE and there would be no removal of reads mapping on the negative strand.
Another thing is: did you discarded short reads (<20 nts) before mapping? Otherwise, very short reads are likely to map on positive or negative strands by chance. Finally: before the alignment on the transcriptome, did you mapped on rRNA and tRNA sequences to get rid of potential "contaminations" from these RNAs? I am thinking that for some reason they might map on the wrong strand and since they are usually quite a lot - especially the rRNAs - they may affect the final result.


About this

> By the way, I know you are the expert on the ribo-seq analysis. I just wonder do I need to add "-m" option which lets bowtie forbids the muti-mapping reads export to bam/sam. I think it is confused if ribo-seq small reads map to more than one transcript. But it will cause nearly 40% of reads to remove in the bowtie.

I think that by mapping on the transcriptome, that includes multiple transcript isoforms (i.e. multiple similar sequences where a particular read can match), it is reasonable to keep muti-mapping reads for downstream analysis. You can think of reducing the maximum number of possible alignments for each read (5-10 should be fine, based on the average numbr of isoforms), but I would not discard all of them.

Best,
Fabio

**Comment by Xuan0318** [comment] 2021-02-09 14:28
Hi Fabio,

Thank you for your help! I filtered the sequence that was shorter than 15nt. Then if I allow muti-map in the bowtie. The result will be better. But there were still more than 10% percent sequences mapping to the negative strand. The same things happened in all six ribo-seq files.

Then I tested rRNA. But the amount of rRNA is really small:
```
$ wc -l 1612880155_rrna.fq   
1008 1612880155_rrna.fq
$ wc -l 1612880155_nonrrna.fq
19175688 1612880155_nonrrna.fq
```
It means there is only 250 reads map to rRNA. So, it will not affect the result.
I still do not know the reason. I will check the sequences that map to negative strand and try to find the reason. I will update if I solve it. 

Best,
Yuxuan

**Comment by Xuan0318** [comment] 2021-02-09 14:28
Hi Fabio,

Thank you for your help! I filtered the sequence that was shorter than 15nt. Then if I allow muti-map in the bowtie. The result will be better. But there were still more than 10% percent sequences mapping to the negative strand.

Then I tested rRNA. But the amount of rRNA is really low:
```
$ wc -l 1612880155_rrna.fq   
1008 1612880155_rrna.fq
$ wc -l 1612880155_nonrrna.fq
19175688 1612880155_nonrrna.fq
```
It means there are only 250 reads map to rRNA. So, it will not affect result.

**Comment by fabiolauria** [comment] 2021-02-09 15:31
I think the best thing to do is to check those sequences, as you suggested. In any case I usually discard reads shorter than 20 nts. There is no much difference with respect to 15 nts, but every nucleotide increase the "specificity" of the read and decrease the chances of random mapping. 5 nts may be the cause of the difference in the percentage of reads mapping on the negative strand (from around 2% to 10%). Another possibility is DNA contamination in the sample so you partially sequenced fragments complementary to the right ones.

As for the rRNA, it's a good thing you only have few reads mapping on them. I'm used to get 50-70% of rRNA (i.e. mapping on an ad hoc data set of ribosomal RNA), this is the reason I raised the issue.

**Comment by Xuan0318** [comment] 2021-02-12 11:05
Hi Fabio,

I have one more question. I checked the _psite_info_ in output file. But I find all of the psite_regions were 5utr in the output file.
```
transcript	end5	psite	end3	length	cds_start	cds_stop	psite_from_start	psite_from_stop	psite_region
ENST00000641515.2	2551	NA	2564	14	61	1041	NA	NA	5utr
ENST00000420190.6	520	NA	549	30	505	1578	NA	NA	5utr
ENST00000420190.6	659	NA	678	20	505	1578	NA	NA	5utr
ENST00000420190.6	850	NA	879	30	505	1578	NA	NA	5utr
ENST00000420190.6	979	NA	1009	31	505	1578	NA	NA	5utr
ENST00000420190.6	994	NA	1024	31	505	1578	NA	NA	5utr
ENST00000420190.6	1324	NA	1353	30	505	1578	NA	NA	5utr
ENST00000420190.6	1443	NA	1474	32	505	1578	NA	NA	5utr
ENST00000437963.5	343	NA	372	30	61	387	NA	NA	5utr
ENST00000342066.8	373	NA	402	30	91	2136	NA	NA	5utr
ENST00000342066.8	492	NA	523	32	91	2136	NA	NA	5utr
ENST00000342066.8	707	NA	737	31	91	2136	NA	NA	5utr
ENST00000342066.8	872	NA	906	35	91	2136	NA	NA	5utr
ENST00000342066.8	1874	NA	1899	26	91	2136	NA	NA	5utr
ENST00000618181.4	431	NA	462	32	81	1751	NA	NA	5utr
```
for this line as an example:
```
transcript	end5	psite	end3	length	cds_start	cds_stop	psite_from_start	psite_from_stop	psite_region
ENST00000641515.2	2551	NA	2564	14	61	1041	NA	NA	5utr
```
The ribosome located from 2551 to 2564 and the cds was from 61 to 1041. It located on the 3' end, but I do not know why the result told me it located on 5utr. In addition, all the _psite_ in output is NA and _psite_region_ are NA or 5utr. If there are somethings wrong with the output could I locate psite region and psite by myself according to the information including cds_start,	cds_stop, end5 and end3. 

Thank you for your help all the time again！

Best,
Yuxuan

**Comment by fabiolauria** [comment] 2021-02-12 12:56
Hi Yuxuan,
_psite_regions_ is always **5utr** because for some reason the identification of the P-site within the reads failed. You can clearly see this from the the NA-filled _psite_ column.

In principle, once the position of the p-site has been identified and stored in the _psite_ column (its location should be between the end5 and the end3), riboWaltz fills the columns _psite_from_start_, _psite_from_stop_ and finally _psite_regions_. Since the psite value is missing, there is a cascade of wrong computations and assignments that lead _psite_regions_ to be set to **5utr**.

I think something went wrong when you run the **psite** function rather than **psite_info**. Which is the output of **psite**? is it a data table of non-empty columns? Do columns _corrected_offset_from_5_ and _corrected_offset_from_3_ contain any NA?

I just tested the current version of **psite** and **psite_info**. Everything worked fine, so there are no internal errors. If your data contain exceptions riboWaltz can't handle, we will find out soon enough and try to fix it.

Best,
Fabio

**Comment by Xuan0318** [comment] 2021-02-19 03:33
Hi Fabio,

Sorry for my late reply. I found that I make mistake on **psite**. Now it works well! Thank you again for your help all the time.

Best,
Yuxuan

**Comment by fabiolauria** [comment] 2021-02-19 08:30
Hi Yuxuan,
Thank for your reply. I'm glad to know everything is fine.
I'm going to close this thread. Please feel free to open a new issue or write to me should you encounter additional problems. 

Best
Fabio

**Closed by fabiolauria** 2021-02-19 08:30 UTC
