### ISSUE TITLE
create_annotation problem

### ISSUE THREAD

**Issue by kabilov** [LabTranslationalArchitectomics/riboWaltz#25] opened 2019-11-30 07:30 UTC
Hi!

I have a problem with create_annotation function. An error occurs while trying to import the gtf file.

an<--create_annotation(gtfpath = file2, txdb = NULL, dataSource = NA, organism = NA)
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Error in FUN(left) :wrong argument for unary operator

I tried to import different gtf. Could you explain error?

Best wishes,
Marsel

**Comment by fabiolauria** [comment] 2019-12-01 21:28
Hi Marsel,
I just run the current GutHub version of _create_annotation_ using human annotation GTFs and it works properly. Thus I have a couple of questions for you: is file2 a character string of the complete path to the GTF file, including its extension? Are you sure the data.table package is correctly loaded (it should be since riboWaltz is loaded, but could you please check it out)?

Bests,
Fabio

**Comment by kabilov** [comment] 2019-12-02 05:03
Dear Fabio,

I'm sorry, I forgot to write that it was a custom gtf file.

Bio1    CLCBIO    5UTR    25    42    .    +    .    gene_id NNN; transcript_id NNN.1
Bio1    CLCBIO    3UTR    64    110    .    +    .    gene_id NNN; transcript_id NNN.1
Bio1    CLCBIO    CDS    43    60    .    +    0    gene_id NNN; transcript_id NNN.1
Bio1    CLCBIO    exon    25    110    .    +    .    gene_id NNN; transcript_id NNN.1
Bio1    CLCBIO    start_codon    43    45    .    +    .    gene_id NNN; transcript_id NNN.1
Bio1    CLCBIO    end_codon    61    63    .    +    .    gene_id NNN; transcript_id NNN.1

1) Yes, the file2 has extension and full path
2) the data.table package not shows any problem

Best wishes,
Marsel

**Comment by fabiolauria** [comment] 2019-12-02 10:12
Hi Marsel,
I think there is something going on in the GTF file. With this I mean that maybe one transcript ID appears multiple times with different length of CDS and UTRs or different start and stop codon positions. Or maybe some information is missing?.
I'm saying so because I run _create_annotation_ with the few lines you posted above as GTF input and it worked: I got a one-row data table with the correct length for each RNA region. I deduce your ERROR is not caused by the function or the general structure of the custom GTF, but by something specific in it.
Unfortunately I cannot be of much help here.

Bests,
Fabio

**Comment by fabiolauria** [comment] 2020-05-25 13:49
Hi,
hope everything is fine. I'm going to close this issue now.
If you need more help, just let me know.

Fabio

**Closed by fabiolauria** 2020-05-25 13:49 UTC
